# Generated by Django 4.1.3 on 2022-12-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_start', models.DateTimeField()),
                ('event_end', models.DateTimeField()),
            ],
        ),
    ]
